export const ROUTES = {
  dashboard: '/',
  login: '/login',
  dailyReports: '/daily-reports',
  dailyReportDetail: (id: string) => `/daily-reports/${id}`,
  dailyReportCreate: '/daily-reports/new',
  dailyReportEdit: (id: string) => `/daily-reports/${id}/edit`,
  weeklyReports: '/weekly-reports',
  weeklyReportDetail: (id: string) => `/weekly-reports/${id}`,
  weeklyReportCreate: '/weekly-reports/new',
  weeklyReportEdit: (id: string) => `/weekly-reports/${id}/edit`,
  monthlyReports: '/monthly-reports',
  monthlyReportDetail: (id: string) => `/monthly-reports/${id}`,
  monthlyReportCreate: '/monthly-reports/new',
  tasks: '/tasks',
  taskDetail: (id: string) => `/tasks/${id}`,
  taskEdit: (id: string) => `/tasks/${id}/edit`,
  projects: '/projects',
  projectCreate: '/projects/new',
  projectDetail: (id: string) => `/projects/${id}`,
  projectEdit: (id: string) => `/projects/${id}/edit`,
} as const;
